max_train_iters:  500
num_updates_per_iter:  100
total updates:  50000
save_model_name:  edt_hopper-medium-replay-v2_100_model_24-04-26-02-28-26.pt
save_model_path:  dt_runs/edt_hopper-medium-replay-v2_100_model_24-04-26-02-28-26.pt
log_csv_name:  edt_hopper-medium-replay-v2_100_log_24-04-26-02-28-26.csv
log_csv_path:  dt_runs/edt_hopper-medium-replay-v2_100_log_24-04-26-02-28-26.csv
============================================================
start time: 24-04-26-02-28-26
============================================================
device set to: cuda
dataset path: data/hopper-medium-replay-v2.pkl
model save path: dt_runs/edt_hopper-medium-replay-v2_100_model_24-04-26-02-28-26.pt
log csv save path: dt_runs/edt_hopper-medium-replay-v2_100_log_24-04-26-02-28-26.csv
num of trajs: 2041
/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py:118: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/gym/spaces/box.py:84: UserWarning: [33mWARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Traceback (most recent call last):
  File "scripts/train_edt.py", line 401, in <module>
    train(args)
  File "scripts/train_edt.py", line 168, in train
    ).to(device)
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/root/miniconda3/envs/mujoco/lib/python3.7/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW